Feature/nijo 747 agency payment method endpoint
happy-travel/edo-api pull request #219
Opened 2020-09-18 14:16 UTC by Raibo

2020-09-21 06:05 UTC, mingazhev requested changes

2020-09-21 06:05 UTC, mingazhev commented on Api/AdministratorServices/AgencySystemSettingsManagementService.cs
> +                _context.Update(systemSettings);
Did you check this?
Looks like not working

2020-09-21 14:54 UTC, Raibo commented on Api/AdministratorServices/AgencySystemSettingsManagementService.cs
> +                _context.Update(systemSettings);
How could I possibly check this, if the migration will be only executed upon merging :(

2020-09-21 15:48 UTC, mingazhev commented on Api/AdministratorServices/AgencySystemSettingsManagementService.cs
> +                _context.Update(systemSettings);
You can execute migration, check it and then revert

2020-09-21 15:49 UTC, mingazhev commented on Api/AdministratorServices/AgencySystemSettingsManagementService.cs
> +                _context.Update(systemSettings);
look for EF cli dotnet tool

2020-09-22 01:22 UTC, Raibo commented on Api/AdministratorServices/AgencySystemSettingsManagementService.cs
> +                _context.Update(systemSettings);
I looked closely to this bit of code and immediately it became obvious why this won't work.
Fixed. 
I did not apply the migration, but given the logic in `SetAvailabilitySearchSettings` works, all should be fine.

2020-09-22 01:24 UTC, Raibo commented on Api/AdministratorServices/AgencySystemSettingsManagementService.cs
> +        private Task<bool> IsAgencyExist(int agencyId) => _context.Agencies.AnyAsync(a => a.Id == agencyId && a.IsActive);
Did as you suggest. 
Now `GetAvailabilitySearchSettings` and `SetAvailabilitySearchSettings` checks existance of an agency among active ones. Is this OK?

2020-09-22 01:26 UTC, Raibo commented on Api/AdministratorServices/AgencySystemSettingsManagementService.cs
> +        public async Task<Result> SetDisplayedPaymentOptions(DisplayedPaymentOptionsSettings settings, int agencyId)
This sounds not like "a deeper approach", but as a different one.
I think this should be discussed.

2020-09-22 09:58 UTC, mingazhev approved these changes

2020-09-22 10:29 UTC, merged