Refund credit card payments with payfort
happy-travel/edo-api pull request #275
Opened 2020-10-30 15:30 UTC by Raibo

2020-11-02 09:40 UTC, mingazhev requested changes

2020-11-02 09:40 UTC, mingazhev commented on Api/Services/Payments/CreditCards/CreditCardMoneyCaptureService.cs
> +            int agentId)
Why refund is in "CaptureService"? There are two anthonym operations there - to operate with authorized money. Refund looks like not suitable there

2020-11-02 09:40 UTC, mingazhev commented on Api/Services/Payments/CreditCards/CreditCardMoneyCaptureService.cs
> +                    : Result.Success(default(CreditCardRefundResult));
Result could be omitted there

2020-11-02 09:40 UTC, mingazhev commented on Api/Services/Payments/CreditCards/CreditCardMoneyCaptureService.cs
> +                    : Result.Success(default(CreditCardRefundResult));
And returning default value looks not valid there.
If we did not do anything in payfort, anyway we need to return a valid object, containing all the refund data, maybe with zero amount, not default value.
In case of default, at least useless data is written to audit log

2020-11-02 09:40 UTC, mingazhev commented on Api/Services/Payments/Payfort/PayfortService.cs
> +                using (var response = await client.PostAsync(_options.PaymentUrl, requestContent))
Please use the modern "using" syntax for new code

2020-11-02 11:46 UTC, Raibo commented on Api/Services/Payments/CreditCards/CreditCardMoneyCaptureService.cs
> +            int agentId)
Well, refund is basically a cancel of capture, so I thought it would suit here, but if you insist, I'll make new service for this operation

2020-11-02 11:59 UTC, kirillta commented on Api/Services/Payments/CreditCards/CreditCardMoneyCaptureService.cs
> +            int agentId)
I agree, but do we need another name for the service?

2020-11-03 01:59 UTC, Raibo commented on Api/Services/Payments/CreditCards/CreditCardMoneyCaptureService.cs
> +                    : Result.Success(default(CreditCardRefundResult));
There is some additional detail to this part of code, which matters:
`CreditCardRefundResult` object fields make only a part of the audit record. Money amount is taken not from it, but from `CreditCardRefundMoneyRequest` object.
`CreditCardRefundResult` is responsible only for payfort response, which never happened in case of zero amount, so it is obvious that no values could be substituted there. 

The audit record is not useless, it contains additional data, as mentioned above.
Also, added `MerchantReference` to returned `CreditCardRefundResult` for more complete record, since it is known even without payfort response.

2020-11-03 02:03 UTC, Raibo commented on Api/Services/Payments/CreditCards/CreditCardMoneyCaptureService.cs
> +            int agentId)
How about `CreditCardCaptureVoidRefundService`?

2020-11-03 07:45 UTC, mingazhev commented on Api/Services/Payments/CreditCards/CreditCardMoneyCaptureService.cs
> +            int agentId)
Ok for another service name, ok for separate service.
Not Ok for "CreditCardCaptureVoidRefundService" and other names with enumerating method names.

2020-11-03 07:46 UTC, mingazhev commented on Api/Services/Payments/CreditCards/CreditCardMoneyCaptureService.cs
> +                    : Result.Success(default(CreditCardRefundResult));
You're right, it's all good there

2020-11-03 10:01 UTC, Raibo commented on Api/Services/Payments/CreditCards/CreditCardMoneyCaptureService.cs
> +            int agentId)
Couldn't come up with any good name, so moved to "RefundService"

2020-11-03 10:05 UTC, mingazhev approved these changes

2020-11-03 12:55 UTC, kirillta approved these changes

2020-11-05 06:57 UTC, merged